#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ENC(Y/DEn2MCiPqx3GfV8q8W/+TcKr//4NF3/I18lgc/1/MS8qY9C/xvWSBQWaHbe7ipTp0Pw8jjnyrcKCuwJP+eEtiNQDx+ymk1UEgi+4LMSp5+e/U5RN6d8BNnmtVnPAj4el8MJTyuAlQ8MyrxsiPUeQ==)
#    username: admin
#    password: challenge66
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true  # SQL pretty print
#
#jasypt:
#  encryptor:
#    bean: jasyptStringEncryptor
#mail:
#  address:
#    admin: 141000Lee@gmail.com # ??? ?? ?? ? ??
#jwt:
#  key: ${JWT_SECRET_KEY} # ??? ?? ??
#  access-token-expiration-minutes: 30
#  refresh-token-expiration-minutes: 600
